apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - name: node-app
        image: app-2-image
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_DATABASE
          value: node_crud
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: root
---
apiVersion: v1
kind: Service
metadata:
  name: app-2-service
spec:
  type: NodePort
  selector:
    app: app-2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001 # Use a different port to avoid conflicts
