apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: django-app
        image: jksingh13/stgi-app1
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_DB
          value: abc_db
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: app-1-service
spec:
  type: NodePort
  selector:
    app: app-1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30002
