apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - name: node-app
        image: jksingh13/stgi-app2
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          value: mysql-dev  # Change this to mysql-dev to match the service name
        - name: MYSQL_DATABASE
          value: node_crud
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: root
