apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Daemon       off
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/pods/*/*/*.log
        Exclude_Path      /var/log/pods/*/*fluent-bit*.log, /var/log/pods/*/*coredns*.log, /var/log/pods/*/*kube-controller-manager*.log, /var/log/pods/*/*storage-provisioner*.log, /var/log/pods/*/*kube-scheduler*.log, /var/log/pods/*/*kube-proxy*.log, /var/log/pods/*/*kube-apiserver*.log, /var/log/pods/*/*etcd*.log  
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        DB                /var/log/flb_kube.db

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    [FILTER]
        Name                geoip
        Match               kube.*
        Key                 ip_address               
        Add_Field           true                     
        Include             city_name,country_code

    [FILTER]
        Name                record_transformer
        Match               kube.*
        Record              new_time ${time}
        Time_Format         "%Y-%m-%d %H:%M:%S"

    [FILTER]
        Name                grep
        Match               kube.*
        Regex               log  "ERROR|WARN|INFO"

    [FILTER]
        Name                lua
        Match               kube.*
        script              extract_fields.lua  
        call                extract_fields

    [FILTER]
        Name              grep
        Match             kube.*
        Regex             kubernetes.pod_name nginx.*

    [FILTER]
        Name              grep
        Match             kube.*
        Regex             kubernetes.namespace_name production.*

    [FILTER]
        Name              grep
        Match             kube.*
        Regex             kubernetes.labels.app webapp.*

    [OUTPUT]
        Name          influxdb
        Match         *
        Host          influxdb
        Port          8086
        bucket        SegFault
        org           STGI
        sequence_tag  _seq
        http_token    7ETF8X3ZThuQrarZxNeHIsa4QmqjEjmgjJzDQY9PnqegvnM884YbpzDOUolunsn29LxX8FRW1sQPb822-25KrA==

  parsers.conf: |
    [PARSER]
        Name              docker
        Format            json
        Time_Key          time
        Time_Format       %Y-%m-%dT%H:%M:%S.%L
        Time_Keep         On

  extract_fields.lua: |
    function extract_fields(tag, timestamp, record)
        -- Custom logic to extract additional fields from the log
        return 1, timestamp, record
        end

        -- Calculate CPU utilization as a percentage
        if total_time > 0 then
            cpu_utilization = (active_time / total_time) * 100
        else
            cpu_utilization = 0
        end

        -- Add the CPU utilization to the log record
        record["cpu_utilization"] = cpu_utilization
        return 1, timestamp, record
    end
