apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
spec:
  type: LoadBalancer  # Change to NodePort if you want
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: spring-boot-app
