version: '3.8'

services:
  influxdb:
    image: influxdb:2.7 # You can specify the latest version
    container_name: influxdb_container
    ports:
      - "8086:8086" # InfluxDB's default port
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
      - INFLUXDB_BUCKET=mybucket
      - INFLUXDB_ORG=myorg
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped

volumes:
  influxdb_data:
