apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  type: ClusterIP  # You can use NodePort or LoadBalancer based on your needs
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: influxdb
